import { Mail, Phone, MapPin, Linkedin, Globe, ArrowRight } from "lucide-react";

const TimelineTemplate = ({ data, accentColor = "#1a1a2e" }) => {
    const formatDate = (dateStr) => {
        if (!dateStr) return "";
        const [year, month] = dateStr.split("-");
        return new Date(year, month - 1).toLocaleDateString("en-US", {
            year: "numeric",
            month: "short",
        });
    };

    // Inline style helpers for dynamic accent color (can't be generated by Tailwind JIT)
    const accentBg = { backgroundColor: accentColor };
    const accentText = { color: accentColor };
    const accentShadowRing = { boxShadow: `0 0 0 2px ${accentColor}` };
    const accentBgFaint = { backgroundColor: `${accentColor}08` };
    const accentBorderFaint = { borderColor: `${accentColor}40` };

    return (
        <div className="max-w-4xl mx-auto bg-stone-50 text-gray-900 font-sans">

            {/* ── Header ── */}
            <header className="relative overflow-hidden px-16 pt-14 pb-12" style={accentBg}>
                {/* Decorative circles */}
                <div className="absolute -top-12 -right-12 w-56 h-56 rounded-full opacity-5 bg-white" />
                <div className="absolute -bottom-16 left-10 w-36 h-36 rounded-full opacity-5 bg-white" />

                <h1 className="relative z-10 text-5xl font-black tracking-tight text-white leading-none mb-5">
                    {data?.personal_info?.full_name || "Your Name"}
                </h1>

                <div className="relative z-10 flex flex-wrap gap-5">
                    {data?.personal_info?.email && (
                        <span className="flex items-center gap-1.5 text-xs text-white/80 font-light tracking-wide">
                            <Mail size={11} className="opacity-70" />
                            {data.personal_info.email}
                        </span>
                    )}
                    {data?.personal_info?.phone && (
                        <span className="flex items-center gap-1.5 text-xs text-white/80 font-light tracking-wide">
                            <Phone size={11} className="opacity-70" />
                            {data.personal_info.phone}
                        </span>
                    )}
                    {data?.personal_info?.location && (
                        <span className="flex items-center gap-1.5 text-xs text-white/80 font-light tracking-wide">
                            <MapPin size={11} className="opacity-70" />
                            {data.personal_info.location}
                        </span>
                    )}
                    {data?.personal_info?.linkedin && (
                        <span className="flex items-center gap-1.5 text-xs text-white/80 font-light tracking-wide">
                            <Linkedin size={11} className="opacity-70" />
                            {data.personal_info.linkedin}
                        </span>
                    )}
                    {data?.personal_info?.website && (
                        <span className="flex items-center gap-1.5 text-xs text-white/80 font-light tracking-wide">
                            <Globe size={11} className="opacity-70" />
                            {data.personal_info.website}
                        </span>
                    )}
                </div>
            </header>

            {/* ── Summary ── */}
            {data?.professional_summary && (
                <section className="px-16 py-9 border-b border-stone-200">
                    <p className="text-sm leading-relaxed text-gray-500 font-light max-w-2xl">
                        {data.professional_summary}
                    </p>
                </section>
            )}

            {/* ── Experience ── */}
            {data?.experience?.length > 0 && (
                <section className="px-16 py-12">
                    <p className="text-[10px] font-medium tracking-[3px] uppercase mb-1" style={accentText}>
                        Career
                    </p>
                    <h2 className="text-2xl font-bold mb-8" style={accentText}>
                        Experience
                    </h2>

                    {/* Timeline rail */}
                    <div className="relative pl-7">
                        {/* Vertical line */}
                        <div
                            className="absolute left-0 top-1.5 bottom-0 w-px"
                            style={{ background: `linear-gradient(to bottom, ${accentColor}, ${accentColor}18)` }}
                        />

                        {data.experience.map((exp, i) => (
                            <div key={i} className="relative pb-9 last:pb-0">
                                {/* Dot */}
                                <div
                                    className="absolute -left-[29px] top-1.5 w-2.5 h-2.5 rounded-full border-2 border-stone-50"
                                    style={{ ...accentBg, ...accentShadowRing }}
                                />

                                <div className="flex items-baseline justify-between gap-3 flex-wrap mb-0.5">
                                    <span className="text-base font-bold text-gray-900">
                                        {exp.position}
                                    </span>
                                    <span className="text-[11px] font-medium tracking-wide" style={accentText}>
                                        {formatDate(exp.start_date)} — {exp.is_current ? "Present" : formatDate(exp.end_date)}
                                    </span>
                                </div>

                                <p className="text-xs font-semibold mb-2.5 tracking-wide" style={accentText}>
                                    {exp.company}
                                </p>

                                {exp.description && (
                                    <p className="text-sm leading-relaxed text-gray-500 font-light whitespace-pre-line">
                                        {exp.description}
                                    </p>
                                )}
                            </div>
                        ))}
                    </div>
                </section>
            )}

            {/* ── Education + Skills ── */}
            {(data?.education?.length > 0 || data?.skills?.length > 0) && (
                <div className="grid grid-cols-2 border-t border-stone-200">
                    {/* Education */}
                    {data?.education?.length > 0 && (
                        <section className="px-10 py-10 pr-8 border-r border-stone-200">
                            <p className="text-[10px] font-medium tracking-[3px] uppercase mb-1" style={accentText}>
                                Academic
                            </p>
                            <h2 className="text-xl font-bold mb-6" style={accentText}>
                                Education
                            </h2>
                            <div className="space-y-5">
                                {data.education.map((edu, i) => (
                                    <div key={i} className="pb-5 border-b border-stone-200 last:border-0 last:pb-0">
                                        <p className="text-sm font-bold text-gray-900 mb-0.5">
                                            {edu.degree}{edu.field ? ` in ${edu.field}` : ""}
                                        </p>
                                        <p className="text-xs font-semibold mb-1" style={accentText}>
                                            {edu.institution}
                                        </p>
                                        <p className="text-xs text-gray-400 tracking-wide">
                                            {edu.is_current ? "Present" : formatDate(edu.graduation_date)}
                                            {edu.gpa ? ` · GPA ${edu.gpa}` : ""}
                                        </p>
                                    </div>
                                ))}
                            </div>
                        </section>
                    )}

                    {/* Skills */}
                    {data?.skills?.length > 0 && (
                        <section className="px-8 py-10" style={accentBgFaint}>
                            <p className="text-[10px] font-medium tracking-[3px] uppercase mb-1" style={accentText}>
                                Expertise
                            </p>
                            <h2 className="text-xl font-bold mb-6" style={accentText}>
                                Skills
                            </h2>
                            <div className="flex flex-wrap gap-2">
                                {data.skills.map((skill, i) => (
                                    <span
                                        key={i}
                                        className="text-xs font-medium px-3 py-1.5 rounded border bg-white tracking-wide"
                                        style={{ ...accentText, ...accentBorderFaint }}
                                    >
                                        {skill}
                                    </span>
                                ))}
                            </div>
                        </section>
                    )}
                </div>
            )}

            {/* ── Projects ── */}
            {data?.projects?.length > 0 && (
                <section className="px-16 py-12 border-t border-stone-200">
                    <p className="text-[10px] font-medium tracking-[3px] uppercase mb-1" style={accentText}>
                        Work
                    </p>
                    <h2 className="text-2xl font-bold mb-8" style={accentText}>
                        Projects
                    </h2>
                    <div className="grid grid-cols-2 gap-5">
                        {data.projects.map((proj, i) => (
                            <div
                                key={i}
                                className="bg-white rounded-lg border border-stone-200 p-6 hover:shadow-md transition-shadow duration-200"
                            >
                                {/* Accent bar */}
                                <div className="w-7 h-0.5 rounded-full mb-4" style={accentBg} />

                                <p className="text-sm font-bold text-gray-900 mb-1">{proj.name}</p>
                                {proj.type && (
                                    <p className="text-[10px] font-semibold uppercase tracking-widest mb-2 opacity-60" style={accentText}>
                                        {proj.type}
                                    </p>
                                )}
                                {proj.tech_stack && (
                                    <p className="text-xs text-gray-400 italic mb-2.5">{proj.tech_stack}</p>
                                )}
                                {proj.description && (
                                    <p className="text-xs leading-relaxed text-gray-500 font-light">
                                        {proj.description}
                                    </p>
                                )}
                                {proj.project_link && (
                                    <a
                                        href={proj.project_link}
                                        target="_blank"
                                        rel="noreferrer"
                                        className="inline-flex items-center gap-1 text-xs font-semibold mt-3 underline-offset-2 hover:underline tracking-wide"
                                        style={accentText}
                                    >
                                        View Project <ArrowRight size={10} />
                                    </a>
                                )}
                            </div>
                        ))}
                    </div>
                </section>
            )}
        </div>
    );
};

export default TimelineTemplate;